### ISSUE TITLE
A connector should not be marked as dirty while a response is being written.

### ISSUE THREAD

**Issue by aleknandrius** [rolandkrueger/vaadin-by-example#1]
**Do you have idea about this issue?**

java.lang.IllegalStateException: A connector should not be marked as dirty while a response is being written.
    at com.vaadin.ui.ConnectorTracker.markDirty(ConnectorTracker.java:505)
    at com.vaadin.server.AbstractClientConnector.markAsDirty(AbstractClientConnector.java:141)
    at com.vaadin.ui.AbstractSelect.fireItemSetChange(AbstractSelect.java:1734)
    at com.vaadin.ui.AbstractSelect.containerItemSetChange(AbstractSelect.java:1701)
    at com.vaadin.ui.ComboBox.containerItemSetChange(ComboBox.java:514)
    at com.vaadin.data.util.AbstractContainer.fireItemSetChange(AbstractContainer.java:242)
    at com.vaadin.data.util.AbstractInMemoryContainer.fireItemsAdded(AbstractInMemoryContainer.java:1012)
    at com.vaadin.data.util.AbstractBeanContainer.addAll(AbstractBeanContainer.java:716)
    at com.vaadin.data.util.BeanItemContainer.addAll(BeanItemContainer.java:176)
    at com.asaoweb.xxxxx.backoffice.components.SuggestingContainer.filterItems(SuggestingContainer.java:70)
    at com.asaoweb.xxxxx.backoffice.components.SuggestingContainer.addFilter(SuggestingContainer.java:53)
    at com.vaadin.data.util.AbstractBeanContainer.addContainerFilter(AbstractBeanContainer.java:385)
    at com.vaadin.ui.ComboBox.getOptionsWithFilter(ComboBox.java:434)
    at com.vaadin.ui.ComboBox.paintContent(ComboBox.java:254)
    at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65)
    at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:82)
    at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:145)

**Comment by rolandkrueger** [comment]
What I found out so far is the following: when execution reaches `com.vaadin.ui.ComboBox.containerItemSetChange(ComboBox.java:514)`, then the variable `ComboBox.isPainting` appears to be `false` in your scenario. This is strange, since that value should actually be `true`. When I step through the code of my demo with the debugger, `isPainting` is always `true` so that the code that triggers the exception is skipped. So the question is, why is this variable `false` in your scenario?

What exact version of Vaadin are you using?

**Comment by kleidt** [comment]
I got the same error message. I had 3 ComboBoxes which has shared the same BeanItemContainer like (simplified):
`Collection<Bean> beans = ...;`
`BeanItemContainer<Bean> container = new BeanItemContainer<>(Bean.class, beans);`
`ComboBox cb1 = new ComboBox();`
`cb1.setContainerDataSource(container);`
`ComboBox cb2 = new ComboBox();`
`cb2.setContainerDataSource(container);`

I found that ComboBox.isPainting is set to true in paintContent() of the SECOND ComboBox (when I start searching something) and before finishing the call (and finally resetting isPainting to false), containerItemSetChange() is called from the FIRST ComboBox where isPainting is false.

The following changes fixing the problem:
`Collection<Bean> beans = ...;`
`ComboBox cb1 = new ComboBox();`
`cb1.setContainerDataSource(new BeanItemContainer<>(Bean.class, beans));`
`ComboBox cb2 = new ComboBox();`
`cb2.setContainerDataSource(new BeanItemContainer<>(Bean.class, beans));`

I think Vaadin must either ensure a Container is only used once or handle this case correctly.

**Comment by FiruzzZ** [comment]
I have a similar problem with `org.​vaadin.​addons.​comboboxmultiselect` trying to add an item
Using Vaadin 7.7.13
